name: Plugin CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/upload-artifact@v4
        with:
          name: configcat-sdk
          path: ${{ github.workspace }}

  plugin-ci:
    uses:  outoftheboxplugins/BuildMachines/.github/workflows/compile-plugin.yml@master
    with:
      plugin_code: configcat-sdk
    secrets: inherit
