name: Plugin CD

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-engine-plugin:
    runs-on: ubuntu-latest
    name: 📦 Package Plugin
    steps:
      - uses: actions/checkout@v3

      - name: Install via vcpkg
        run: |
          pwd
          ls -l
          echo "${{ github.workspace }}"
      
      - uses: jossef/action-set-json-field@v2.1
        with:
          file: "${{ github.workspace }}/ConfigCat.uplugin"
          field: VersionName
          value: "${{ github.ref_name }}"

      - name: Archive files
        run: |
          zip -r archive.zip . -x LICENSE

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "archive.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: ${{ github.ref }}
          name: "${{ github.ref_name }}"
